layout: sidebar
style: light

destination: /var/www/html

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"


resume:
  education:
    - organization: Duke University
      position: Computer Science
      date: Class of 2022
      location: Durham, NC

      description:
        text: Computer Science major with a certificate in Innovation & Entrepreneurship
        points:
          - Co-founder of Duke University Neural Engineering Undergraduate Union and Journal Club
          - Taken Data Structures and Algorithms, Computer Architecture, Intro to Data Science, Technology Commercialization
          - Member of DUU DevOps committee and Duke Marching Band

    - organization: Loveland High School
      position: ""
      date: Class of 2018
      location: Cincinnati, OH

      description:
        points:
          - 4.44 GPA, Top 1% of class out of 350
          - AP Calculus BC, AP Computer Science A
          - Math Team, school winner of Ameircan Math Competition 10 and 12

    - organization: University of Cincinnati
      position: ""
      date: Summer and Fall 2017
      location: Cincinnati, OH

      description:
        points:
          - College Physics I and Lab course, dual enrollment
          - DITLE three-week intensive program - computer fundamentals, application development, 
            database and networking concepts. Served as TA for other teams and members. Built 
            an idea-sharing website (backend and frontend) as capstone project.

  experience:
  
    - organization: Realtime Robotics
      position: Robotics Engineering Intern
      date: Summer 2020
      location: Boston, MA
      
      description:
        points:
          - Worked on a development team to help create the future of hardware-accelerated robotics motion planning.
          - Designed and implemented a cutting-edge synchronized runtime system for highly optimized multi-robot choreographies.
          - Created debugging tools using ROS, RViz, and C++ to visualize and monitor multi-robot optimization tasks.
  
    - organization: GE Aviation
      position: Digital Technology Intern (Supply Chain)
      date: Summer 2019
      location: Cincinnati, OH
      
      description:
        points:
          - Worked on a machine learning system for industrial inspection, saving over $125k/yr per minute of labor cost avoidance.
          - Designed and implemented a scalable and maintainable high-performance distributed system architecture for load-balancing high-volume DICOM/DICONDE Volumetric-CT scan data among scanners, inspection machines, archives, and other systems. This system led to improved stability and efficiency for an industrial inspection ecosystem supporting thousands of parts weekly in the Turbine Airfoils Value Stream.
          - Rapidly designed and implemented a C# desktop application for managing and tagging scan analysis results for ML model training, resulting in an increasingly large training dataset and improved model accuracy.
          - Led migration to GitHub of turbine airfoils inspection software dev team, and created robust documentation for related tools and ecosystem, facilitating increased productivity, flexibility, and maintainability of software products.
          - Worked directly with an internal customer, often travelling on-location to better understand the customer's needs, leading to a software deployment across several GE shops.
          - Created a Virtual Reality proof-of-concept interface for inspecting volumetric CT scans of additively manufactured turbine blades.
          - Designed and implemented high-performance solutions for evaluating model efficiency using TIBCO Spotfire and R, improving an existing system by delivering powerful visualizations and reports.
  
    - organization: GE Aviation
      position: Digital Technology Intern (Cybersecurity - Advanced Detection Solutions)
      date: Summer 2018
      location: Cincinnati, OH

      description:
        points:
          - Worked on an agile development team supporting cybersecurity tools that protect GE Aviation’s $26 billion in annual revenue.
          - Led proof-of-concept to develop machine learning capabilities in identifying malicious emails from 3-4 million emails daily.
          - Delivered productivity enhancements for GE Aviation’s main security alert console, speeding time to triage and resolve potential security threats.
          - Implemented static application security testing (SAST) and addressed code vulnerabilities for security tools.
          - Led evaluation of low-code-no-code solution to speed enhancements of endpoint security solution protecting 45,000+ company laptops, workstations, and shopfloor machines.
          - Developed data analytics using Elasticsearch and Kibana to help security analysts triage tens of thousands of alerts annually.
          - Supported and improved a distributed Elasticsearch (ELK Stack) cluster responsible for managing hundreds of daily security alerts, leading to improved performance and stability.

    - organization: Project Purple
      position: Lead Programmer
      date: April 2017
      location: Cincinnati, OH

      description:
        points:
          - Presented at Consumer Electronics Show in Las Vegas, National winner 
            of Young Innovators to Watch scholarship
          - Winner of the RevolutionUC hackathon from over 40 college teams. Project 
            uses Unity, C#, and the Oculus Rift.

    - organization: Illumen Media (digital marketing startup)
      position: Full Stack Web Developer
      date: November 2017 – May 2018
      location: Cincinnati, OH

      description:
        points:
          - Created a fully-featured, large, complex application intended for accountants to manage the workflows of their clients as they step through verifying several documents (built with Django/Python).
          - Worked directly with clients to gather requirements and iterate during the development process, leading to successful delivery and deployment of several website for local Cincinnati businesses.
          - Created and maintained client websites utilizing WordPress, HTML, CSS, PHP, SQL, JavaScript, etc.

    - organization: INTERalliance of Greater Cincinnati
      position: Internal Systems Manager
      date: 2017-2018
      location: Cincinnati, OH

      description:
        points:
          - Created the website for TechOlympics 2018, the nation’s largest high school tech conference. Created 30+ pages of the website and implemented complex registration workflows supporting over 550 student attendees.
          - <a href="https://techolympics.org">http://techolympics.org</a>
          - As a result, the website reached a 25% conversion rate, quickly and very effectively accomplishing its purpose. At very little cost to the INTERalliance, this year's TechOlympics website was immensely successful and received praise and recognition from several of the attending IT professionals, as well as countless students, faculty members, and volunteers. The website is flexible, scalable, and easy to update, and therefore is being re-used.
          - Responsible for all INTERalliance IT requirements. In charge of INTERalliance website, internal and external communications, accounts, and internal software.

    - organization: Campus Enterprises LLC
      position: Backend Developer (BlueTech)
      date: Jan 2019 - Apr 2019
      location: Durham, NC

      description:
        points:
          - Worked closely with a team of developers to create a web application leveraging psychometric analysis to determine financial loan eligibility for individuals in Nigeria, leading to a successful delivery of software to an external customer.
          - Leveraged Django/Python to create a RESTful API constituting the backend of the application, and contributed/maintained the React-based frontend.
          
    - organization: Duke University Union (DUU)
      position: Web Designer
      date: Jan 2019 - Mar 2019
      location: Durham, NC
      
      description:
        points:
          - Member of the Duke University Union DevOps committee, designed, created, and maintains the DUU website (duuke.org), providing information about Duke's largest event programming organization.

projects:
  featured:
    - vasilescur/ambush
    - vasilescur/dcc
    - vasilescur/pfl

  hackathon:
    - vasilescur/LyricLearner
    - vasilescur/Occurren
    - vasilescur/FocusFriend
    - vasilescur/Inspire

  fun:
    - vasilescur/dcc
    - vasilescur/mAh-Battery
    - vasilescur/Thermostat
    - vasilescur/Noun.js
    - vasilescur/vscode-Better-MIPS
    - vasilescur/Java-Rendering-Engine
    - vasilescur/Processing
    - vasilescur/GE-Intern-C-Obfuscation-Challenge
    - vasilescur/GUI-Framework
    - vasilescur/Reddit-Daily-Programmer

  community:
    - vasilescur/project-purple
    - vasilescur/LovelandShowcase
    - vasilescur/music-in-schools

  datavis:
    - vasilescur/Polyinstrumental-Cacophony
  
  school:
    - vasilescur/ambush
    - vasilescur/Computer
    - vasilescur/DecSci-Group-9
    - vasilescur/ola

  opensource:
    - vasilescur/sdk
