layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

projects:
  featured:
    - vasilescur/techolympics-website
    - vasilescur/pfl
    - vasilescur/DecSci-Group-9
    - vasilescur/Noun.js
    - vasilescur/Time
    - vasilescur/LyricLearner

  hackathon:
    - vasilescur/LyricLearner
    - vasilescur/Occurren
    - vasilescur/FocusFriend
    - vasilescur/Inspire

  fun:
    - vasilescur/mAh-Battery
    - vasilescur/TreeLevel
    - vasilescur/Reddit-Daily-Programmer
    - vasilescur/vscode-Better-MIPS
    - vasilescur/Processing
    - vasilescur/GE-Intern-C-Obfuscation-Challenge
    - vasilescur/Java-Rendering-Engine
    - vasilescur/GUI-Framework

  community:
    - vasilescur/project-purple
    - vasilescur/LovelandShowcase
    - vasilescur/music-in-schools

  datavis:
    - vasilescur/Time
    - vasilescur/Polyinstrumental-Cacophony
  
  school:
    - vasilescur/Computer
    - vasilescur/WOTO-Time
    - vasilescur/ola

  opensource:
    - vasilescur/sdk

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"