layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"


resume:
  education:
    - organization: Duke University
      position: Computer Science
      date: Class of 2022
      location: Durham, NC

      description:
        text: Computer Science major with a certificate in Innovation & Entrepreneurship
        points:
          - 4.0 GPA
          - Taken Data Structures and Algorithms, Computer Architecture, Intro to Data Science, Technology Commercialization
          - Member of DUU DevOps committee and Duke Marching Band

    - organization: Loveland High School
      position: ""
      date: Class of 2018
      location: Cincinnati, OH

      description:
        points:
          - 4.44 GPA, Top 1% of class out of 350
          - AP Calculus BC, AP Computer Science A
          - Math Team, school winner of Ameircan Math Competition 10 and 12

    - organization: University of Cincinnati
      position: ""
      date: Summer and Fall 2017
      location: Cincinnati, OH

      description:
        points:
          - College Physics I and Lab course, dual enrollment
          - DITLE three-week intensive program - computer fundamentals, application development, 
            database and networking concepts. Served as TA for other teams and members. Built 
            an idea-sharing website (backend and frontend) as capstone project.

  experience:
    - organization: GE Aviation
      position: Digital Technology Intern (Cybersecurity - Advanced Detection Solutions)
      date: Summer 2018
      location: Cincinnati, OH

      description:
        points:
          - Worked on an agile development team supporting cybersecurity tools that 
            protect GE Aviation’s $26 billion annual revenue
          - Delivered productivity enhancements for GE’s main security alert console, 
            reducing time to triage and resolve security threats
          - Led proof-of-concept to develop machine learning capabilities in identifying 
            malicious emails from 3-4 million emails daily
          - Led evaluation of low-code solution to enhance endpoint security solution 
            protecting 45,000+ company workstations.
          - Implemented static application security testing (SAST) and addressed code 
            vulnerabilities for security tools.
          - Developed data analytics to help security analysts triage tens of thousands 
            of alerts annually.

    - organization: Project Purple
      position: Lead Programmer
      date: April 2017
      location: Cincinnati, OH

      description:
        points:
          - Presented at Consumer Electronics Show in Las Vegas, National winner 
            of Young Innovators to Watch scholarship
          - Winner of the RevolutionUC hackathon from over 40 college teams. Project 
            uses Unity, C#, and the Oculus Rift.

    - organization: Illumen Media (digital marketing startup)
      position: Full Stack Web Developer
      date: November 2017 – May 2018
      location: Cincinnati, OH

      description:
        points:
          - Developed all-in-one solution for accountants to manage complex tax rerturn 
            document workflows including knowledge-based-authentication.

    - organization: INTERalliance of Greater Cincinnati
      position: Internal Systems Manager
      date: 2017-2018
      location: Cincinnati, OH

      description:
        points:
          - Built website for TechOlympics, the nation’s largest high school tech 
            conference (techolympics.org). 
          - Responsible for all IT requirements - websites, communications, accounts, 
            and business logic

projects:
  featured:
    - vasilescur/techolympics-website
    - vasilescur/dcc
    - vasilescur/pfl

  hackathon:
    - vasilescur/LyricLearner
    - vasilescur/Occurren
    - vasilescur/FocusFriend
    - vasilescur/Inspire

  fun:
    - vasilescur/dcc
    - vasilescur/mAh-Battery
    - vasilescur/Thermostat
    - vasilescur/Noun.js
    - vasilescur/vscode-Better-MIPS
    - vasilescur/Java-Rendering-Engine
    - vasilescur/Processing
    - vasilescur/GE-Intern-C-Obfuscation-Challenge
    - vasilescur/GUI-Framework
    - vasilescur/Reddit-Daily-Programmer

  community:
    - vasilescur/project-purple
    - vasilescur/LovelandShowcase
    - vasilescur/music-in-schools

  datavis:
    - vasilescur/Polyinstrumental-Cacophony
  
  school:
    - vasilescur/Computer
    - vasilescur/DecSci-Group-9
    - vasilescur/ola

  opensource:
    - vasilescur/sdk
